---
deployment:
  tasks:
    - export DEPLOYPATH=/home/adminmlc/cardona
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -R . $DEPLOYPATH
    - cd $DEPLOYPATH && /usr/local/bin/npm install --prefer-offline 2>&1
    - cd $DEPLOYPATH && /usr/local/bin/npm run build:server 2>&1
